services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  pgadmin-data: