zones = {
    1040: {
        "brackets": {"min": 461, "max": 518, "bucket": 3, "type": "Item Level"},
        "difficulties": [
            {"id": 4, "name": "Heroic", "sizes": [25, 10]},
            {"id": 3, "name": "Normal", "sizes": [25, 10]},
        ],
        "encounters": [
            {"id": 1507, "name": "Imperial Vizier Zor'lok", "journalID": 0},
            {"id": 1504, "name": "Blade Lord Ta'yak", "journalID": 0},
            {"id": 1463, "name": "Garalon", "journalID": 0},
            {"id": 1498, "name": "Wind Lord Mel'jarak", "journalID": 0},
            {"id": 1499, "name": "Amber-Shaper Un'sok", "journalID": 0},
            {"id": 1501, "name": "Grand Empress Shek'zeer", "journalID": 0},
            {"id": 1409, "name": "Protectors of the Endless", "journalID": 0},
            {"id": 1505, "name": "Tsulong", "journalID": 0},
            {"id": 1506, "name": "Lei Shi", "journalID": 0},
            {"id": 1431, "name": "Sha of Fear", "journalID": 0},
        ],
        "expansion": {"id": 1004, "name": "Mists of Pandaria"},
        "frozen": False,
        "name": "HoF / ToES",
    },
    1036: {
        "brackets": None,
        "difficulties": [{"id": 3, "name": "Normal", "sizes": [40]}],
        "encounters": [
            {"id": 251118, "name": "Patchwerk", "journalID": 0},
            {"id": 251111, "name": "Grobbulus", "journalID": 0},
            {"id": 251108, "name": "Gluth", "journalID": 0},
            {"id": 251120, "name": "Thaddius", "journalID": 0},
            {"id": 251117, "name": "Noth the Plaguebringer", "journalID": 0},
            {"id": 251112, "name": "Heigan the Unclean", "journalID": 0},
            {"id": 251115, "name": "Loatheb", "journalID": 0},
            {"id": 251107, "name": "Anub'Rekhan", "journalID": 0},
            {"id": 251110, "name": "Grand Widow Faerlina", "journalID": 0},
            {"id": 251116, "name": "Maexxna", "journalID": 0},
            {"id": 251113, "name": "Instructor Razuvious", "journalID": 0},
            {"id": 251109, "name": "Gothik the Harvester", "journalID": 0},
            {"id": 251121, "name": "The Four Horsemen", "journalID": 0},
            {"id": 251119, "name": "Sapphiron", "journalID": 0},
            {"id": 251114, "name": "Kel'Thuzad", "journalID": 0},
        ],
        "expansion": {"id": 1000, "name": "Classic"},
        "frozen": False,
        "name": "Naxxramas",
    },
}
